# https://starship.rs/config/

# ---------------------------
#          GENERAL
# ---------------------------

format = '$all'

palette = 'ofir'
[palettes.ofir]
cyan = '#66d9ef'
purple = '#ae81ff'
light_red = '#f92672'
pink = '#fc68e1'
teal = '#3ae0b4'
# green = '#a6e22e'
green = '#07b516'

# ---------------------------
#          CUSTOMS
# ---------------------------
[custom.git_repo]
command = "git remote -v | head -n 1 | sed -e 's/origin\t//' | sed -e 's/ (fetch)//' | sed -s 's,.*:.*/,,'"
detect_files = ['.git']
when = '''  cat .git | grep "\.git" | grep "/modules/" '''
symbol = ''
style = 'light_red'
format = '[$symbol $output]($style) '

# ---------------------------
#          MODULES
# ---------------------------
[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[username]
format = '[$user]($style):'
style_user = 'pink'
show_always = true

[directory]
truncate_to_repo = false
style = 'purple'
truncation_length = 999

[git_branch]
style = 'teal'
symbol = ''
format = '[\($symbol$branch(:$remote_branch)\)]($style) '

[git_commit]
style = 'cyan'
tag_disabled = false
tag_symbol = ' | '

[git_status]
disabled = true

[git_metrics]
disabled = true

[aws]
disabled = true

[golang]
style='bold yellow'
