# https://starship.rs/config/

# ---------------------------
#          GENERAL
# ---------------------------

# format = '$all'
# Using "manual" all to put "time" before line_break
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$netns\
$shell\
$character"""

palette = 'ofir'
[palettes.ofir]
cyan = '#66d9ef'
purple = '#ae81ff'
light_red = '#f92672'
pink = '#fc68e1'
teal = '#3ae0b4'
# green = '#a6e22e'
green = '#07b516'
red = '#eb0909'

# ---------------------------
#          CUSTOMS
# ---------------------------
[custom.git_repo]
command = "git remote -v | head -n 1 | sed -e 's/origin\t//' | sed -e 's/ (fetch)//' | sed -s 's,.*:.*/,,'"
detect_files = ['.git']
when = '''  cat .git | grep "\.git" | grep "/modules/" '''
symbol = ''
style = 'light_red'
format = '[$symbol $output]($style) '

# ---------------------------
#          MODULES
# ---------------------------
[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[username]
format = '[$user]($style)'
style_user = 'pink'
style_root = 'red'
show_always = true

[directory]
truncate_to_repo = false
style = 'bold purple'
truncation_length = 999
format=':[$path]($style)[$read_only]($read_only_style) '

[git_branch]
style = 'teal'
symbol = ''
format = '[\($symbol$branch(:$remote_branch)\)]($style) '

[git_commit]
style = 'cyan'
tag_disabled = false
tag_symbol = ' | '

[git_status]
disabled = true

[git_metrics]
disabled = true

[aws]
disabled = true

[time]
disabled = false
format = '[\($time\)]($style) '

[golang]
style='bold yellow'

[hostname]
ssh_symbol = '@'
style = 'bold green'
format = '[$ssh_symbol$hostname]($style)'
